version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - configs/bot.env
      - configs/db.env
      - configs/slack.env
      - configs/exchange.env
