version: '3'
services:
  bot-mona:
    image: docker.pkg.github.com/canpok1/trading-bot-rust/bot:latest
    env_file:
      - configs/bot.env
      - configs/bot-mona.env
      - configs/db.env
      - configs/slack.env
      - configs/exchange.env
    networks:
      - trading-bot-network
  bot-plt:
    image: docker.pkg.github.com/canpok1/trading-bot-rust/bot:latest
    env_file:
      - configs/bot.env
      - configs/bot-plt.env
      - configs/db.env
      - configs/slack.env
      - configs/exchange.env
    networks:
      - trading-bot-network
  bot-etc:
    image: docker.pkg.github.com/canpok1/trading-bot-rust/bot:latest
    env_file:
      - configs/bot.env
      - configs/bot-etc.env
      - configs/db.env
      - configs/slack.env
      - configs/exchange.env
    networks:
      - trading-bot-network
networks:
  trading-bot-network:
    external:
      name: trading-bot-network
