env_files = [
    "./configs/bot.env",
    "./configs/bot-mona.env",
    "./configs/db.env",
    "./configs/slack.env",
    "./configs/exchange.env"
]

[tasks.run]
command = "cargo"
args = ["run", "--bin", "bot"]
