@startuml trading-bot-rust
start

:初期化;

repeat
    :情報取得;

    :DB保存;
    note right
        ・トレンドライン
        ・レジスタンスライン
        ・サポートライン
        ・約定待ちレート
    end note

    if (保有コイン) then (なし)
        :DB保存;
        note right
            ・残高JPY
        end note
    endif

    partition 行動決定 {
        if (未使用コイン) then (一定以上)
            :行動リストに売り注文を追加;
        endif

        if (未決済注文のレート) then (現レートとの差が一定以上)
            :行動リストに損切りを追加;
        endif
        if (未決済注文のレート) then (現レートとの差が一定未満)
        elseif (残高JPY) then (注文不可)
        elseif (短期レジスタンスライン) then (ブレイクアウト)
            :行動リストにエントリー追加;
        elseif (短期サポートライン) then (リバウンド)
            :行動リストにエントリー追加;
        endif
    }

    partition 行動 {
        while (未実施の行動がある？) is (yes)
            if (エントリー) then (yes)
                :成行買い注文;
                :約定待ち;
                :指値売り注文;
            elseif (損切り) then (yes)
                :注文キャンセル;
                :キャンセル待ち;
                :成行売り注文;
            elseif (売り注文) then (yes)
                :注文キャンセル;
                :キャンセル待ち;
                :指値売り注文;
            endif
        endwhile
    }

    :待機;
repeat while

stop
@enduml